# generated by datamodel-codegen:
#   filename:  cache_overpass_787942e60b73c7cb84d4b5549b03cb82.json
#   timestamp: 2025-08-30T11:45:58+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class Osm3s(BaseModel):
    timestamp_osm_base: str
    copyright: str


class Tags(BaseModel):
    network_type: str = Field(..., alias='network:type')
    rcn_ref: Optional[str] = None
    expected_rcn_route_relations: Optional[str] = None
    panoramax: Optional[str] = None
    survey_date: Optional[str] = Field(None, alias='survey:date')
    traffic_calming: Optional[str] = None
    mapillary: Optional[str] = None
    panoramax_0: Optional[str] = Field(None, alias='panoramax:0')
    expected_rwn_route_relations: Optional[str] = None
    rwn_ref: Optional[str] = None
    fixme: Optional[str] = None
    wikimedia_commons: Optional[str] = None
    check_date: Optional[str] = None
    check_date_tactile_paving: Optional[str] = Field(
        None, alias='check_date:tactile_paving'
    )
    crossing: Optional[str] = None
    crossing_island: Optional[str] = Field(None, alias='crossing:island')
    highway: Optional[str] = None
    tactile_paving: Optional[str] = None
    panoramax_1: Optional[str] = Field(None, alias='panoramax:1')
    crossing_markings: Optional[str] = Field(None, alias='crossing:markings')
    crossing_signals: Optional[str] = Field(None, alias='crossing:signals')
    bicycle: Optional[str] = None
    network: Optional[str] = None
    ref: Optional[str] = None
    route: Optional[str] = None
    type: Optional[str] = None
    name: Optional[str] = None


class Member(BaseModel):
    type: str
    ref: int
    role: str


class Element(BaseModel):
    type: str
    id: int
    lat: Optional[float] = None
    lon: Optional[float] = None
    tags: Optional[Tags] = None
    members: Optional[List[Member]] = None
    nodes: Optional[List[int]] = None


class GeneratedModel(BaseModel):
    version: float
    generator: str
    osm3s: Osm3s
    elements: List[Element]
